ha, it turns out you cannot index floats
After turning them off this popped beautiful gem up:
ObjectBoxException: failed to create store: 10001 State condition failed in assignIdsForProperty:476: indexId <= catalog.lastIndexId()