StorageException: use actual type in string representation.
This regression was introduced after adding subclasses of
StorageException. With this change subclasses now correctly print their
name in the string representation.